// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAif8a-F8tMSnoLGqIcwt7CZj-5o5B-II',
    appId: '1:858980520851:web:3cdefef33ca3e58ee9ce66',
    messagingSenderId: '858980520851',
    projectId: 'news-app-36f34',
    authDomain: 'news-app-36f34.firebaseapp.com',
    storageBucket: 'news-app-36f34.firebasestorage.app',
    measurementId: 'G-3Y23C0GMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSGr3Ls1GNkL6oxRIPXdMwxWxLJoAvNU',
    appId: '1:858980520851:android:4a53ec6f48ec22c9e9ce66',
    messagingSenderId: '858980520851',
    projectId: 'news-app-36f34',
    storageBucket: 'news-app-36f34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSe-xY40mxZPh3zl58V00bWShkWCDKUQc',
    appId: '1:858980520851:ios:80f6f60e1c2dffb0e9ce66',
    messagingSenderId: '858980520851',
    projectId: 'news-app-36f34',
    storageBucket: 'news-app-36f34.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSe-xY40mxZPh3zl58V00bWShkWCDKUQc',
    appId: '1:858980520851:ios:80f6f60e1c2dffb0e9ce66',
    messagingSenderId: '858980520851',
    projectId: 'news-app-36f34',
    storageBucket: 'news-app-36f34.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAif8a-F8tMSnoLGqIcwt7CZj-5o5B-II',
    appId: '1:858980520851:web:dc6e8f7f8792fd60e9ce66',
    messagingSenderId: '858980520851',
    projectId: 'news-app-36f34',
    authDomain: 'news-app-36f34.firebaseapp.com',
    storageBucket: 'news-app-36f34.firebasestorage.app',
    measurementId: 'G-9TG9VJSJJN',
  );

}