// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6Uah2EahA9GKPo3yftTmUJN4U5seymY',
    appId: '1:219967732081:web:f6dacdf526403dc3611ed0',
    messagingSenderId: '219967732081',
    projectId: 'news-app-22aaf',
    authDomain: 'news-app-22aaf.firebaseapp.com',
    storageBucket: 'news-app-22aaf.firebasestorage.app',
    measurementId: 'G-JYY2L9Z0SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbP9eWn1D0ZKCnPBdqDxCpupUjMiVZwhs',
    appId: '1:219967732081:android:b92f58b1889eb4b2611ed0',
    messagingSenderId: '219967732081',
    projectId: 'news-app-22aaf',
    storageBucket: 'news-app-22aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAriLo29TjdoGQkII4vcA5kSqM0mZNoaLM',
    appId: '1:219967732081:ios:7caee9b23a72e167611ed0',
    messagingSenderId: '219967732081',
    projectId: 'news-app-22aaf',
    storageBucket: 'news-app-22aaf.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAriLo29TjdoGQkII4vcA5kSqM0mZNoaLM',
    appId: '1:219967732081:ios:7caee9b23a72e167611ed0',
    messagingSenderId: '219967732081',
    projectId: 'news-app-22aaf',
    storageBucket: 'news-app-22aaf.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ6Uah2EahA9GKPo3yftTmUJN4U5seymY',
    appId: '1:219967732081:web:c7e35800c1720c72611ed0',
    messagingSenderId: '219967732081',
    projectId: 'news-app-22aaf',
    authDomain: 'news-app-22aaf.firebaseapp.com',
    storageBucket: 'news-app-22aaf.firebasestorage.app',
    measurementId: 'G-LLE2BYSTKT',
  );
}
